name: Format PR branch

on:
  pull_request:
    types: [synchronize, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run v fmt on src/
        run: v fmt -w src/

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/'
          message: 'style: auto-format V code in src/'
          default_author: github_actions
