name: CI

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: write   # to push formatting commits
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch (or master on push)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Install V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      # ---- Formatting (only on PRs) ----
      - name: Format V code in src/
        if: github.event_name == 'pull_request'
        run: v fmt -w src/

      - name: Commit & push formatting changes
        if: github.event_name == 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/'
          message: 'style: auto-format V code in src/'
          default_author: github_actions

      # ---- Build & Test ----
      - name: Build lilly
        run: v run ./make.vsh build

      - name: Run Tests
        run: v run ./make.vsh verbose-test